version: '3'

volumes:
  mysqlData:
      driver: local

services:
  mysql:
      image: mysql:5.7
      restart: always
      volumes:
        - mysqlData:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8888:80'

  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      volumes:
       - ./jboss:/opt/jboss
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
      ports:
        - 80:8080
      depends_on:
        - mysql
